on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  
jobs:
  test-original-dockerfile:
    uses: ls1intum/.github/.github/workflows/test-original-dockerfile.yml@main
    with:
      docker-file: browser.Dockerfile
      image-name: ghcr.io/ls1intum/theia/original_theia
      docker-context: .
    secrets: inherit

  build-and-push-base:
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      docker-file: images/base-ide/BaseDockerfile
      image-name: ghcr.io/ls1intum/theia/base
      docker-context: .
    secrets: inherit

  build-and-push:
    needs: build-and-push-base
    strategy:
      matrix:
        docker-context: ['.']
        include:
          - docker-file: images/java-17/ToolDockerfile
            image-name: ghcr.io/ls1intum/theia/java-17
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      docker-file: ${{ matrix.docker-file }}
      image-name: ${{ matrix.image-name }}
      docker-context: ${{ matrix.docker-context }}
    secrets: inherit
  
  