on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  
jobs:
  build-and-push-base:
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      docker-file: images/base-ide/BaseDockerfile
      image-name: ghcr.io/ls1intum/theia/base
      docker-context: .
    secrets: inherit

  build-and-push:
    needs: build-and-push-base
    strategy:
      matrix:
        docker-context: ['.']
        include:
          - docker-file: images/java17-21/ToolDockerfile
            image-name: ghcr.io/ls1intum/theia/java17-21
          - docker-file: images/swift/ToolDockerfile
            image-name: ghcr.io/ls1intum/theia/swift
            build-args: |
              "BUILDER_IMAGE"=swift:5.9.2-focal"
              "RUNTIME_IMAGE=swift:5.9.2-focal"
              "SWIFTLINT_VERSION=0.54.0"
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      docker-file: ${{ matrix.docker-file }}
      image-name: ${{ matrix.image-name }}
      docker-context: ${{ matrix.docker-context }}
    secrets: inherit
  
  