on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  
jobs:
  build-and-push-base:
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@feat/include-label-for-docker-images
    with:
      docker-file: images/base-ide/BaseDockerfile
      image-name: ghcr.io/ls1intum/theia/base
      docker-context: .
      tags: "2024-06-21"
    secrets: inherit

  build-and-push:
    needs: build-and-push-base
    strategy:
      fail-fast: false
      matrix:
        docker-context: ['.']
        include:
          - docker-file: images/java-17/ToolDockerfile
            image-name: ghcr.io/ls1intum/theia/java-17
            tags: "2024-06-21"
          - docker-file: images/swift/ToolDockerfile
            image-name: ghcr.io/ls1intum/theia/swift
            build-args: |
              "BUILDER_IMAGE=swift:5.9.2-focal"
              "RUNTIME_IMAGE=swift:5.9.2-focal"
              "SWIFTLINT_VERSION=0.54.0"
            tags: "2024-06-21"
          - docker-file: images/c/ToolDockerfile
            image-name: ghcr.io/ls1intum/theia/c
            tags: "2024-06-21"
          - docker-file: images/ocaml/ToolDockerfile
            image-name: ghcr.io/ls1intum/theia/ocaml
            tags: "2024-06-21"
          - docker-file: images/python/ToolDockerfile
            image-name: ghcr.io/ls1intum/theia/python
            tags: "2024-06-21"
          - docker-file: images/haskell/ToolDockerfile
            image-name: ghcr.io/ls1intum/theia/haskell
            tags: "2024-06-21"
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@feat/include-label-for-docker-images
    with:
      docker-file: ${{ matrix.docker-file }}
      image-name: ${{ matrix.image-name }}
      docker-context: ${{ matrix.docker-context }}
      tags: ${{ matrix.tags }}
    secrets: inherit
  
  